# Generated by Django 5.0.4 on 2024-05-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_remove_note_body_note_description_note_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='owner_id',
            new_name='owner_id',
        ),
    ]
